name: render

on: [push]

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      DIR: draft
      FILE: main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install TeXlive
        run: sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      
      - name: Compile LaTeX
        run: latexmk -pdf Travel_Plans.tex
      
      - name: Commit to pages
        run: |
          git switch --orphan gh-pages
          git add Travel_Plans.pdf
          git commit -m "Deploying to GitHub Pages"
          git push origin gh-pages --force
